name: Sincronización

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Git
        run: |
          git config user.name "NewWorld Bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Obtener rama repo
        run: |
          git fetch origin repo:repo
          git checkout repo

      - name: Descargar catálogo de Keiyoushi
        run: |
          curl -fL \
            "https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.json" \
            -o /tmp/keiyoushi-index.json

      - name: Crear catálogo NewWorld
        run: |
          jq '
            .extensionList.extensions
            | map(
                . as $extension
                |
                (
                  $extension.sources
                  | map(
                      select(
                        .language == "es"
                        or .language == "es-419"
                        or .language == "en"
                      )
                    )
                ) as $sources
                |
                select(($sources | length) > 0)
                |
                {
                  name: $extension.name,
                  pkg: $extension.packageName,
                  apk: ($extension.resources.apkUrl | split("/")[-1]),
                  lang: (
                    $extension.packageName
                    | split(".")[4]
                  ),
                  code: ($extension.versionCode | tonumber),
                  version: $extension.versionName,
                  nsfw: (
                    if $extension.contentWarning == "CONTENT_WARNING_NSFW"
                    then 1
                    else 0
                    end
                  ),
                  sources: (
                    $sources
                    | map({
                        name: .name,
                        lang: .language,
                        id: .id,
                        baseUrl: .homeUrl
                      })
                  )
                }
              )
          ' /tmp/keiyoushi-index.json > index.min.json

      - name: Mostrar cantidad de extensiones
        run: |
          echo "Extensiones encontradas:"
          jq 'length' index.min.json

      - name: Comprobar APK
        run: |
          echo "APK descargados:"
          find apk -type f -name "*.apk" | wc -l

      - name: Guardar cambios
        run: |
          git add index.min.json apk/

          if git diff --cached --quiet; then
            echo "No hay cambios."
            exit 0
          fi

          git commit -m "Actualizar extensiones"

      - name: Subir cambios
        run: |
          git push origin repo
